name: Bug Report
description: Create a report to help us improve.
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
  - type: textarea
    id: environment
    attributes:
      label: Environment
  - type: textarea
    id: context
    attributes:
      label: Additional context
